### ISSUE TITLE
你好编译报错.\main.go:21:14: undefined: bin

### ISSUE THREAD

**Issue by reghtml** [del-xiong/miniblink#11]
.\main.go:21:14: undefined: bin

这个是什么意思哦
我的代码就是示例里边的

package main

import (
	"github.com/del-xiong/miniblink"
	"github.com/elazarl/go-bindata-assetfs"
	"log"
)

func main() {
	//设置调试模式
	miniblink.SetDebugMode(true)

	//初始化miniblink模块
	err := miniblink.InitBlink()
	if err != nil {
		log.Fatal(err)
	}

	//注册虚拟网络文件系统到域名app
	miniblink.RegisterFileSystem("app", &assetfs.AssetFS{
		Asset:     bin.Asset,
		AssetDir:  bin.AssetDir,
		AssetInfo: bin.AssetInfo,
	})

	//新建view,加载URL
	view := miniblink.NewWebView(false, 1366, 920)
	//直接加载虚拟文件系统中的网页
	view.LoadURL("http://app/index.html")
	view.SetWindowTitle("Golang GUI Application")
	view.MoveToCenter()
	view.ShowWindow()
	view.ShowDevTools()

	defer view.DestroyWindow()
	mainLock := make(chan bool)
	view.On("destroy", func(_ *miniblink.WebView) {
		view = nil
		mainLock <- true
	})
	<-mainLock
	
}

**Comment by del-xiong** [comment]
演示可以暂时先移除 miniblink.RegisterFileSystem
