### ISSUE TITLE
选择文件 fakepath 问题

### ISSUE THREAD

**Issue by reghtml** [del-xiong/miniblink#20]
使用input的选择文件，得到文件名是 c:/fakepath/1.txt  ,这不是真实路径，这是浏览器为了安全隐藏了文件的真实路径，我想将这个文件路径得到后，通过后端GO去读取这个txt, 但是目前只能得到一个假的路径，这个怎么决绝的呢？

**Comment by del-xiong** [comment]
暂时没注意到有获取真实路径的接口，不过你可以用其他方法实现，js和go是可以互通的，web上点击控件-js捕获事件并调起go函数-go调起系统文件选择框，这样你通过选择框就可以获取到真实路径

**Comment by reghtml** [comment]
谢谢，我目前就是这样做的

**Comment by del-xiong** [comment]
👌
