### ISSUE TITLE
运行代码报错：未定义的webView

### ISSUE THREAD

**Issue by zhixinxiaomage** [del-xiong/miniblink#22]
..\..\..\pkg\mod\github.com\del-xiong\miniblink@v0.0.0-20220609045710-8ec016458de6\webhandler.go:8:13: undefined: WebView

**Comment by del-xiong** [comment]
这看起来不像是库的问题倒像是环境，你可以试试能否访问Webview结构
例如log.Println(reflect.TypeOf(miniblink.WebView{}))
