### ISSUE TITLE
创建多个窗口问题

### ISSUE THREAD

**Issue by reghtml** [del-xiong/miniblink#23]
程序创建了一个主窗口，如果我再
view2 := miniblink.NewWebView(false, 800, 600)
创建一个 窗口2  ，当我关闭窗口2的时候，整个程序关闭了，请问怎么实现在 窗口2 关闭的时候不退出应用程序

**Comment by del-xiong** [comment]
这可能是由于我之前提交的强退pr导致，你可以先回滚该pr试试 https://github.com/del-xiong/miniblink/commit/8ec016458de6e8dabdc5e7d2cf8fa67133ac6503

因为这里窗口销毁涉及到资源未完全释放问题，没有考虑多窗口情况下我就直接退出了最简单
