### ISSUE TITLE
执行JS报错

### ISSUE THREAD

**Issue by jiangyimm** [del-xiong/miniblink#24]
value, err := view.Invoke("localStorage.setItem", "user", "123")

error => 2023/04/26 18:35:03 Illegal invocation

**Comment by del-xiong** [comment]
设置成功没有？我怀疑是因为没返回值报错但执行可能成功了

**Comment by jiangyimm** [comment]
> 设置成功没有？我怀疑是因为没返回值报错但执行可能成功了

https://github.com/jiangyimm/miniblink/commit/8f8457c762259f0cab951ba53cd835503d7d7751     我fork过来后加了个执行js的方法，用这个可以

**Comment by del-xiong** [comment]
ok 针对异常返回值的函数 后面我单独兼容下

**Comment by del-xiong** [comment]
https://github.com/del-xiong/miniblink/pull/25
已更新
